---
version: "3.9"
services:
  # gcc Debug with make
  example-gcc-debug-build-make:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    environment:
      CC: gcc
      CXX: g++
      TARGET: all
      BUILD_TYPE: Debug
      CMAKE_GENERATOR: Unix Makefiles
  # gcc Debug
  example-gcc-debug-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    environment:
      CC: gcc
      CXX: g++
      TARGET: all
      BUILD_TYPE: Debug
      CMAKE_GENERATOR: Ninja
  example-gcc-debug-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    environment:
      CC: gcc
      CXX: g++
      TARGET: all
      BUILD_TYPE: Debug
      CMAKE_GENERATOR: Ninja
  # gcc Release
  example-gcc-release-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    environment:
      CC: gcc
      CXX: g++
      TARGET: all
      BUILD_TYPE: Release
      CMAKE_GENERATOR: Ninja
  example-gcc-release-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    environment:
      CC: gcc
      CXX: g++
      TARGET: all
      BUILD_TYPE: RelWithDebInfo
      CMAKE_GENERATOR: Ninja
  # clang Debug
  example-clang-debug-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    environment:
      CC: clang
      CXX: clang++
      TARGET: all
      BUILD_TYPE: Debug
      CMAKE_GENERATOR: Ninja
  example-clang-debug-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    environment:
      CC: clang
      CXX: clang++
      TARGET: all
      BUILD_TYPE: Debug
      CMAKE_GENERATOR: Ninja
  # clang Release
  example-clang-release-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    environment:
      CC: clang
      CXX: clang++
      TARGET: all
      BUILD_TYPE: Release
      CMAKE_GENERATOR: Ninja
  example-clang-release-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    environment:
      CC: clang
      CXX: clang++
      TARGET: all
      BUILD_TYPE: RelWithDebInfo
      CMAKE_GENERATOR: Ninja
  example-gcc-debug-test-cov:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    environment:
      CC: gcc
      CXX: g++
      TARGET: example-coverage-test
      BUILD_TYPE: Debug
      CMAKE_GENERATOR: Ninja
      CMAKE_ARGS: -DENABLE_COVERAGE:BOOL=TRUE
  example-gcc-release-with-raylib:
    build:
      context: .
      dockerfile: Dockerfile.raylib
      target: build
    environment:
      CC: gcc
      CXX: g++
      TARGET: all
      BUILD_TYPE: Release
      CMAKE_GENERATOR: Ninja
      CMAKE_ARGS: -DUSE_RAYLIB:BOOL=TRUE
  example-mingw-release-build:
    build:
      context: .
      dockerfile: Dockerfile.mingw
      target: build
    environment:
      TARGET: all
      BUILD_TYPE: Release
      CMAKE_GENERATOR: Ninja
      CMAKE_ARGS: -DBUILD_TESTING:BOOL=FALSE -DENABLE_TESTING:BOOL=FALSE
  example-rpi4-release-build:
    build:
      context: .
      dockerfile: Dockerfile.rpi
      target: build
    environment:
      TARGET: all
      BUILD_TYPE: Release
      CMAKE_GENERATOR: Ninja
      CMAKE_ARGS: -DBUILD_TESTING:BOOL=FALSE -DENABLE_TESTING:BOOL=FALSE
  example-emscripten-release-build:
    build:
      context: .
      dockerfile: Dockerfile.emscripten
      target: build
    environment:
      TARGET: all
      BUILD_TYPE: Release
      CMAKE_GENERATOR: Ninja
      CMAKE_ARGS: -DBUILD_TESTING:BOOL=FALSE -DENABLE_TESTING:BOOL=FALSE