#!/bin/bash

${CROSS_CMAKE} -B build -S . -G "${CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DCMAKE_TOOLCHAIN_FILE="${TOOLCHAIN_FILE}" -DVCPKG_TARGET_TRIPLET="${TARGET_TRIPLET}" ${CMAKE_ARGS}
${CROSS_CMAKE} --build build --target "${TARGET}"