#!/bin/bash

cd build

${CROSS_CMAKE} -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DCMAKE_TOOLCHAIN_FILE="${TOOLCHAIN_FILE}" \
    #-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE="/home/project/cmake/mingw-w64-toolchain.cmake" \
    -DVCPKG_TARGET_TRIPLET="${TARGET_TRIPLET}" \
    ${CMAKE_ARGS} ..

${CROSS_MAKE} ${TARGET}