set(VCPKG_TARGET_ARCHITECTURE arm)
set(VCPKG_TARGET_TRIPLET_ARCH arm-rpi)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE /home/project/cmake/rpi-toolchain.cmake)