---
version: "3.9"
services:
  # gcc Debug
  gcc-debug-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    environment:
      CC: gcc
      CXX: g++
      TARGET: all
      BUILD_TYPE: Debug
      CMAKE_GENERATOR: Ninja
  gcc-debug-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    environment:
      CC: gcc
      CXX: g++
      TARGET: all
      BUILD_TYPE: Debug
      CMAKE_GENERATOR: Ninja
  # gcc Release
  gcc-release-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    environment:
      CC: gcc
      CXX: g++
      TARGET: all
      BUILD_TYPE: Release
      CMAKE_GENERATOR: Ninja
  gcc-release-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    environment:
      CC: gcc
      CXX: g++
      TARGET: all
      BUILD_TYPE: RelWithDebInfo
      CMAKE_GENERATOR: Ninja
  # clang Debug
  clang-debug-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    environment:
      CC: clang
      CXX: clang++
      TARGET: all
      BUILD_TYPE: Debug
      CMAKE_GENERATOR: Ninja
  clang-debug-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    environment:
      CC: clang
      CXX: clang++
      TARGET: all
      BUILD_TYPE: Debug
      CMAKE_GENERATOR: Ninja
  # clang Release
  clang-release-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    environment:
      CC: clang
      CXX: clang++
      TARGET: all
      BUILD_TYPE: Release
      CMAKE_GENERATOR: Ninja
  clang-release-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    environment:
      CC: clang
      CXX: clang++
      TARGET: all
      BUILD_TYPE: RelWithDebInfo
      CMAKE_GENERATOR: Ninja
  gcc-debug-test-cov:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    environment:
      CC: gcc
      CXX: g++
      TARGET: tests
      BUILD_TYPE: Debug
      CMAKE_GENERATOR: Ninja
      CMAKE_ARGS: -DENABLE_COVERAGE:BOOL=TRUE