## base image
FROM abeimler/simple-cppbuilder:opengl-libs as base

## build stage
FROM base as build
WORKDIR $VCPKG_ROOT
RUN git pull origin master
RUN $VCPKG_ROOT/vcpkg install raylib
WORKDIR $PROJECT_DIR
COPY . .
CMD ["./docker-build.sh"]

## test stage
FROM build as test
CMD ["./docker-test.sh"]