## base image
FROM abeimler/simple-cppbuilder:opengl-libs as base

## build stage
FROM base as build
RUN ./vcpkg/vcpkg install raylib
COPY . .
CMD ["./docker-build.sh"]

## test stage
FROM build as test
CMD ["./docker-test.sh"]