name: ci-android

on:
  push:
    branches:
      - "main"
      - "feature/ci"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  docker:
    strategy:
      matrix:
        include:
          - build_task: build:base
            test_task: test:base
          - build_task: build:android
            test_task: test:android
            push_tags: 
              - "abeimler/simple-cppbuilder:arm-android"
              - "abeimler/simple-cppbuilder:arm64-android"
              - "abeimler/simple-cppbuilder:x86-android"
              - "abeimler/simple-cppbuilder:x64-android"
          - build_task: build:android:21
            test_task: test:android:21
            push_tags: 
              - "abeimler/simple-cppbuilder:arm-android-21"
              - "abeimler/simple-cppbuilder:arm64-android-21"
              - "abeimler/simple-cppbuilder:x86-android-21"
              - "abeimler/simple-cppbuilder:x64-android-21"
          - build_task: build:android:24
            test_task: test:android:24
            push_tags: 
              - "abeimler/simple-cppbuilder:arm-android-24"
              - "abeimler/simple-cppbuilder:arm64-android-24"
              - "abeimler/simple-cppbuilder:x86-android-24"
              - "abeimler/simple-cppbuilder:x64-android-24"
          - build_task: build:android:25
            test_task: test:android:25
            push_tags: 
              - "abeimler/simple-cppbuilder:arm-android-25"
              - "abeimler/simple-cppbuilder:arm64-android-25"
              - "abeimler/simple-cppbuilder:x86-android-25"
              - "abeimler/simple-cppbuilder:x64-android-25"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup go-task/task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - name: Setup Container Structure Tests
        run: curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker Image  
        run: task ${{ matrix.build_task }}
      #- name: Test
      #  if: ${{ matrix.test_task != '[]' && matrix.test_task != '' }}
      # FIXME: Error: error parsing config file: error unmarshalling config: yaml: unmarshal errors: field unboundEnv not found in type v2.MetadataTest
      #  run: task ${{ matrix.test_task }}
      - name: Login to Docker Hub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Docker Images
        if: ${{ matrix.test_task != '[]' && matrix.test_task != '' && startsWith(github.ref, 'refs/tags/v') }}
        run: for tag in "${{ join(matrix.push_tags, ' ') }}"; do docker push $tag; done
